version: '3'
services:
  airflow-scheduler:
    image: apache/airflow:2.5.0
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__FERNET_KEY=I2oy2tTyQJ3VO5togMgMzHxIQeHjojmivocv5oVla3o=
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./airflow_data:/opt/airflow
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - airflow-webserver
    command: scheduler

  airflow-webserver:
    image: apache/airflow:2.5.0
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__FERNET_KEY=I2oy2tTyQJ3VO5togMgMzHxIQeHjojmivocv5oVla3o=
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./airflow_data:/opt/airflow
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket here
    ports:
      - "8080:8080"
    command: webserver
